package com.myspace.hasrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class hasRulesBo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("inputValue")
	private java.lang.String inputValue;

	@org.kie.api.definition.type.Label("scoringValue")
	private java.lang.Integer scoringValue;

	@org.kie.api.definition.type.Label("scoreName")
	private java.lang.String scoreName;

	@org.kie.api.definition.type.Label("outputName")
	private java.lang.String outputName;

	@org.kie.api.definition.type.Label("outputValue")
	private java.lang.String outputValue;

	@org.kie.api.definition.type.Label("inputName")
	private java.lang.String inputName;

	@org.kie.api.definition.type.Label("benefitLevel")
	private java.lang.String benefitLevel;

	@org.kie.api.definition.type.Label(value = "subBenefitLevel")
	private java.lang.String subBenefitLevel;

	public hasRulesBo() {
	}

	public java.lang.String getInputValue() {
		return this.inputValue;
	}

	public void setInputValue(java.lang.String inputValue) {
		this.inputValue = inputValue;
	}

	public java.lang.Integer getScoringValue() {
		return this.scoringValue;
	}

	public void setScoringValue(java.lang.Integer scoringValue) {
		this.scoringValue = scoringValue;
	}

	public java.lang.String getScoreName() {
		return this.scoreName;
	}

	public void setScoreName(java.lang.String scoreName) {
		this.scoreName = scoreName;
	}

	public java.lang.String getOutputName() {
		return this.outputName;
	}

	public void setOutputName(java.lang.String outputName) {
		this.outputName = outputName;
	}

	public java.lang.String getOutputValue() {
		return this.outputValue;
	}

	public void setOutputValue(java.lang.String outputValue) {
		this.outputValue = outputValue;
	}

	public java.lang.String getInputName() {
		return this.inputName;
	}

	public void setInputName(java.lang.String inputName) {
		this.inputName = inputName;
	}

	public java.lang.String getBenefitLevel() {
		return this.benefitLevel;
	}

	public void setBenefitLevel(java.lang.String benefitLevel) {
		this.benefitLevel = benefitLevel;
	}

	public java.lang.String getSubBenefitLevel() {
		return this.subBenefitLevel;
	}

	public void setSubBenefitLevel(java.lang.String subBenefitLevel) {
		this.subBenefitLevel = subBenefitLevel;
	}

	public hasRulesBo(java.lang.String inputValue,
			java.lang.Integer scoringValue, java.lang.String scoreName,
			java.lang.String outputName, java.lang.String outputValue,
			java.lang.String inputName, java.lang.String benefitLevel,
			java.lang.String subBenefitLevel) {
		this.inputValue = inputValue;
		this.scoringValue = scoringValue;
		this.scoreName = scoreName;
		this.outputName = outputName;
		this.outputValue = outputValue;
		this.inputName = inputName;
		this.benefitLevel = benefitLevel;
		this.subBenefitLevel = subBenefitLevel;
	}

}