package com.myspace.hasrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ruleBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "benefitLevel")
	private java.lang.String benefitLevel;
	@org.kie.api.definition.type.Label(value = "inputName")
	private java.lang.String inputName;
	@org.kie.api.definition.type.Label(value = "memberType")
	private java.lang.String memberType;
	@org.kie.api.definition.type.Label(value = "outputName")
	private java.lang.String outputName;
	@org.kie.api.definition.type.Label(value = "outputValue")
	private java.lang.Integer outputValue;
	@org.kie.api.definition.type.Label(value = "productName")
	private java.lang.String productName;
	@org.kie.api.definition.type.Label(value = "ruleName")
	private java.lang.String ruleName;
	@org.kie.api.definition.type.Label(value = "salary")
	private java.lang.Integer salary;

	public ruleBO() {
	}

	public java.lang.String getBenefitLevel() {
		return this.benefitLevel;
	}

	public void setBenefitLevel(java.lang.String benefitLevel) {
		this.benefitLevel = benefitLevel;
	}

	public java.lang.String getInputName() {
		return this.inputName;
	}

	public void setInputName(java.lang.String inputName) {
		this.inputName = inputName;
	}

	public java.lang.String getMemberType() {
		return this.memberType;
	}

	public void setMemberType(java.lang.String memberType) {
		this.memberType = memberType;
	}

	public java.lang.String getOutputName() {
		return this.outputName;
	}

	public void setOutputName(java.lang.String outputName) {
		this.outputName = outputName;
	}

	public java.lang.Integer getOutputValue() {
		return this.outputValue;
	}

	public void setOutputValue(java.lang.Integer outputValue) {
		this.outputValue = outputValue;
	}

	public java.lang.String getProductName() {
		return this.productName;
	}

	public void setProductName(java.lang.String productName) {
		this.productName = productName;
	}

	public java.lang.String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(java.lang.String ruleName) {
		this.ruleName = ruleName;
	}

	public java.lang.Integer getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Integer salary) {
		this.salary = salary;
	}

	public ruleBO(java.lang.String benefitLevel, java.lang.String inputName,
			java.lang.String memberType, java.lang.String outputName,
			java.lang.Integer outputValue, java.lang.String productName,
			java.lang.String ruleName, java.lang.Integer salary) {
		this.benefitLevel = benefitLevel;
		this.inputName = inputName;
		this.memberType = memberType;
		this.outputName = outputName;
		this.outputValue = outputValue;
		this.productName = productName;
		this.ruleName = ruleName;
		this.salary = salary;
	}

}